services:
  db:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - FPScNet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "4000:8080"
    networks:
      - FPScNet

  backend:
    build: ./backend
    env_file:
      - .env
    container_name: spring-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass
    ports:
      - "8081:8080"
    networks:
      - FPScNet
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    env_file:
      - .env
    container_name: next-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - FPScNet
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:

networks:
  FPScNet:
    driver: bridge

