services:
  db:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - backend

  backend:
    build: ./backend
    container_name: spring_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass
    ports:
      - "8081:8080"
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: next_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - /c/Users/Shuya/Desktop/FPSc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge