logging:
  level:
    org.springframework.security: DEBUG
    com.FPSc: DEBUG
  file:
    name: logs/spring-boot-app.log
spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 1364319913577283594
            client-secret: SvTwPjbi3tiqQXyJIOYAbIeqwWE5g5bQ
            scope: identify,email,connections
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/discord"
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      