spring:
  datasource:
    url: jdbc:mysql://localhost:3300/app_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4
    username: app_user
    password: app_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 1366417359237025823
            client-secret: kRd1ncYmWj4N0Y8jkicfnweP5C5loUxn
            scope: identify
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/discord"
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    com.FPSc: DEBUG

jwt:
  secret: asdfjuoaheaoh12!hoaefaeovaenoaevaGaef?aefaohiehfaenjvoair12-9ef`faefaejae@feafafap:jiwefawji23-923qfvnma
  expiration: 86400
