spring:
  datasource:
    url: jdbc:mysql://db:3306/app_db?useSSL=true&serverTimezone=UTC&characterEncoding=utf8mb4
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${SPRING_DISCORD_CLIENT_ID}
            client-secret: ${SPRING_DISCORD_CLIENT_SECRET}
            scope: identify
            authorization-grant-type: authorization_code
            redirect-uri: ${SPRING_DISCORD_REDIRECT_URI}
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.security.oauth2.client.endpoint.DefaultAuthorizationCodeTokenResponseClient: TRACE
    org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG
jwt:
  secret:
  expiration: 86400

server:
  forward-headers-strategy: native
