import { UserCard } from '@/app/type';

export const testdata: UserCard[] = [
  {
    icon: '',
    name: 'ノア',
    id: 'noah_ow',
    games: [
      { title: 'Overwatch2', rank: 'ゴールド' },
      { title: 'Overwatch2', rank: 'ゴールド' },
      { title: 'Overwatch2', rank: 'ゴールド' },
    ],
    playtime1: { start: '12:00', end: '12:00' },
    playtime2: { start: '12:00', end: '12:00' },
    playstyle: 'わいわい',
    introduction: '自分が管理者です！皆さん一緒に仲良くプレイしましょう！',
    color: 'black',
  },
  {
    icon: '',
    name: 'さくら',
    id: 'sakura_val',
    games: [{ title: 'VALORANT', rank: 'プラチナ' }],
    playtime1: { start: '20:00', end: '23:00' },
    playtime2: { start: '10:00', end: '15:00' },
    playstyle: 'ガチめ',
    introduction: 'VCできる人歓迎！楽しく上達したい！',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'たけし',
    id: 'takeshi_apex',
    games: [{ title: 'Apex Legends', rank: 'ダイヤモンド' }],
    playtime1: { start: '18:00', end: '21:00' },
    playtime2: { start: '13:00', end: '17:00' },
    playstyle: '連携重視',
    introduction: 'ランク一緒に回してくれる人募集中！',
    color: 'black',
  },
  {
    icon: '',
    name: 'ゆい',
    id: 'yui_mc',
    games: [{ title: 'Minecraft', rank: 'なし' }],
    playtime1: { start: '17:00', end: '19:00' },
    playtime2: { start: '11:00', end: '14:00' },
    playstyle: 'まったり',
    introduction: '建築メインで活動中。誰でも歓迎です〜',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'ジョン',
    id: 'john_fortnite',
    games: [{ title: 'Fortnite', rank: 'シルバー' }],
    playtime1: { start: '19:00', end: '22:00' },
    playtime2: { start: '10:00', end: '12:00' },
    playstyle: 'ネタ系',
    introduction: 'ビクロイよりも楽しい時間を！',
    color: 'black',
  },
  {
    icon: '',
    name: 'ミカ',
    id: 'mika_valo',
    games: [{ title: 'VALORANT', rank: 'ゴールド' }],
    playtime1: { start: '18:00', end: '20:00' },
    playtime2: { start: '13:00', end: '16:00' },
    playstyle: '連携重視',
    introduction: '報告しながら楽しくプレイしたい！',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'ケン',
    id: 'ken_cod',
    games: [{ title: 'CoD', rank: 'プラチナ' }],
    playtime1: { start: '21:00', end: '23:00' },
    playtime2: { start: '15:00', end: '18:00' },
    playstyle: 'ガチめ',
    introduction: '勝ちにこだわっていきましょう！',
    color: 'black',
  },
  {
    icon: '',
    name: 'まゆ',
    id: 'mayu_acnh',
    games: [{ title: 'あつ森', rank: 'なし' }],
    playtime1: { start: '09:00', end: '11:00' },
    playtime2: { start: '14:00', end: '16:00' },
    playstyle: 'まったり',
    introduction: '島クリエイト大好き！遊びにきてね🌸',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'リク',
    id: 'riku_rl',
    games: [{ title: 'ロケットリーグ', rank: 'シルバー' }],
    playtime1: { start: '19:00', end: '22:00' },
    playtime2: { start: '10:00', end: '13:00' },
    playstyle: 'わいわい',
    introduction: 'ゴールより笑いを取りたい系男子。',
    color: 'black',
  },
  {
    icon: '',
    name: 'エマ',
    id: 'emma_ow',
    games: [{ title: 'Overwatch2', rank: 'ブロンズ' }],
    playtime1: { start: '17:00', end: '20:00' },
    playtime2: { start: '12:00', end: '15:00' },
    playstyle: '初心者歓迎',
    introduction: '始めたばかりだけど楽しく頑張ってます！',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'ショウ',
    id: 'shou_valo',
    games: [{ title: 'VALORANT', rank: 'イモータル' }],
    playtime1: { start: '22:00', end: '01:00' },
    playtime2: { start: '14:00', end: '18:00' },
    playstyle: 'ガチめ',
    introduction: 'AIM命！ガチでやりたい人集合！',
    color: 'black',
  },
  {
    icon: '',
    name: 'なな',
    id: 'nana_mc',
    games: [{ title: 'Minecraft', rank: 'なし' }],
    playtime1: { start: '15:00', end: '17:00' },
    playtime2: { start: '11:00', end: '13:00' },
    playstyle: 'まったり',
    introduction: 'のんびりサバイバル勢です〜',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'アキラ',
    id: 'akira_apex',
    games: [{ title: 'Apex Legends', rank: 'マスター' }],
    playtime1: { start: '20:00', end: '23:00' },
    playtime2: { start: '09:00', end: '12:00' },
    playstyle: '連携重視',
    introduction: '連携意識でチャンピオン目指す！',
    color: 'black',
  },
  {
    icon: '',
    name: 'カナ',
    id: 'kana_splatoon',
    games: [{ title: 'スプラトゥーン3', rank: 'S+' }],
    playtime1: { start: '16:00', end: '18:00' },
    playtime2: { start: '10:00', end: '13:00' },
    playstyle: 'わいわい',
    introduction: 'ナワバリ大好き！誰でも歓迎〜',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'タクミ',
    id: 'takumi_pubg',
    games: [{ title: 'PUBG', rank: 'ゴールド' }],
    playtime1: { start: '21:00', end: '23:00' },
    playtime2: { start: '13:00', end: '16:00' },
    playstyle: '戦略重視',
    introduction: '立ち回り大事！慎重にいこう！',
    color: 'black',
  },
  {
    icon: '',
    name: 'ミユ',
    id: 'miyu_genshin',
    games: [{ title: '原神', rank: '冒険ランク55' }],
    playtime1: { start: '18:00', end: '21:00' },
    playtime2: { start: '10:00', end: '12:00' },
    playstyle: 'まったり',
    introduction: '探索とストーリー楽しんでます！',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'ソウタ',
    id: 'souta_csgo',
    games: [{ title: 'CS:GO', rank: 'レジェンダリー' }],
    playtime1: { start: '20:00', end: '23:00' },
    playtime2: { start: '14:00', end: '17:00' },
    playstyle: 'ガチめ',
    introduction: '報告と連携で勝利を掴もう！',
    color: 'black',
  },
  {
    icon: '',
    name: 'レナ',
    id: 'rena_pokemon',
    games: [{ title: 'ポケモンユナイト', rank: 'エリート' }],
    playtime1: { start: '17:00', end: '19:00' },
    playtime2: { start: '12:00', end: '14:00' },
    playstyle: 'わいわい',
    introduction: 'かわいいポケモンたちとバトル中！',
    color: 'sakura',
  },
  {
    icon: '',
    name: 'ユウト',
    id: 'yuto_dbd',
    games: [{ title: 'Dead by Daylight', rank: '赤帯' }],
    playtime1: { start: '21:00', end: '01:00' },
    playtime2: { start: '15:00', end: '18:00' },
    playstyle: 'ガチめ',
    introduction: 'キラーもサバイバーもやります！',
    color: 'black',
  },
  {
    icon: '',
    name: 'ハルカ',
    id: 'haruka_sims',
    games: [{ title: 'The Sims 4', rank: 'なし' }],
    playtime1: { start: '10:00', end: '12:00' },
    playtime2: { start: '16:00', end: '18:00' },
    playstyle: 'まったり',
    introduction: '理想の家族作りに夢中です🏠',
    color: 'sakura',
  },
];
